// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asyncButton': string;
  'button': string;
  'row': string;
  'textbox': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
